name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    permissions:
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v7
    - name: Build
      run: swift build -c release --disable-sandbox --arch arm64 --arch x86_64
    - name: Run tests
      run: |
        mkdir -p .build/test-results
        swift test -v --xunit-output .build/test-results/tests.xml --experimental-xunit-message-failure
    - name: Test report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Test Results
        path: .build/test-results/tests-swift-testing.xml
        reporter: java-junit
    - uses: actions/upload-artifact@v7
      if: always()
      with:
          name: test-results
          path: .build/test-results/*.xml
          if-no-files-found: error
    - uses: actions/upload-artifact@v7
      with:
          name: xcresultparser
          path: .build/apple/Products/Release/xcresultparser
