name: Build Release

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c release --arch arm64 --arch x86_64

    - name: Create release artifact
      uses: actions/upload-artifact@v3
      with:
        name: xcresultparser
        path: .build/apple/Products/Release/xcresultparser

    - name: Get release ID
      id: get_release_id
      run: |
        id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }} | jq -r '.id')
        echo "RELEASE_ID=$id" >> $GITHUB_ENV

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets?name=xcresultparser
        asset_path: .build/apple/Products/Release/xcresultparser
        asset_name: xcresultparser
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}
